ruby_on_rails/config/routes.rb
SocialInvaders::Application.routes.draw do

  mount RailsAdmin::Engine => '/radmin', :as => 'rails_admin' if defined? RailsAdmin
  mount Ckeditor::Engine => "/ckeditor"

  class OnlyNonAjaxRequest
    def matches?(request)
      !request.xhr?
    end
  end

  root :to => 'web#index'

  match '/l/:tab_id', to: 'tabs/main#redirect'

  scope 'api', :module => 'api' do
    namespace 'tabs' do
      scope 'answer_contest/:tab_id', :module => 'answer_contest' do
        resources :answers do
        end
      end
      scope 'memo_contest/:tab_id', :module => 'memo_contest' do
        resources :games
      end
    end
  end

  namespace 'api' do
    scope 'pages/:page_id' do
      get '', to: 'pages#show'
      get 'tabs', to: 'pages#tabs'
      match 'add_tab', to: 'pages#add_tab'
      match 'delete_tab', to: 'pages#delete_tab'
    end
    scope 'tabs/:tab_id' do
      get '', to: 'tabs#show'
    end
  end

  match ':controller(/:action(/:id))', controller: /api\/[^\/]+/

  scope 'tpl' do
    match ':controller(/:action(/:id))'

    match 'tabs/:tab_type/edit', to: 'edit_tab#edit'

    match ':controller(/:action(/:id))', :controller => /tabs\/memo_contest\/cms\/[^\/]+/
    match ':controller(/:action(/:id))', :controller => /tabs\/answer_contest\/[^\/]+/

    match ':controller(/:action(/:id))', :controller => /tabs\/answer_contest\/cms\/[^\/]+/
    match ':controller(/:action(/:id))', :controller => /tabs\/answer_contest\/[^\/]+/
  end

  match 'tabs/*a/cms/*b', to: 'admin#index'
  match 'tabs/*a/stats', to: 'admin#index'
  match 'tabs/*a/edit', to: 'edit_tab#index'

  match 'admin/*p', to: 'admin#index'
  match 'page/*p', to: 'admin#index'


  scope "tpl/:locale", :locale => /en|pl/ do
    match '(:action(/:id))(.:format)', :controller => 'web'
  end

  scope "/:locale", :locale => /en|pl/ do
    get '*path', to: 'web#index'
    get '', to: 'web#index'
  end

  match ':controller(/:action(/:id))', :controller => /tabs\/[^\/]+/

  match ':controller(/:action(/:id))', :controller => /alien\/[^\/]+/


  match ':controller(/:action(/:id))', :controller => /tabs\/youtube\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/contact\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/static\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/redirect\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/map\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/topfans\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/files\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/twitter\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/coupons\/[^\/]+/


  match ':controller(/:action(/:id))', :controller => /tabs\/instagram_tab\/[^\/]+/

  match ':controller(/:action(/:id))', :controller => /tabs\/answer_contest\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/memo_contest\/[^\/]+/
  match ':controller(/:action(/:id))', :controller => /tabs\/instagram_contest\/[^\/]+/


  match ':controller(/:action(/:id))'

end

ruby_on_rails/app/helpers/admin_helper.rb
module AdminHelper

  def include_ng_templates(list)
    ret = ''
    list.each do
      ret += "<script type='text/ng-template' id=#{id}_template>"
      ret += render :text => "admin/ng/#{id}"
    end
    raise
  end

  def find_texts(l)
    if l[:dict] == :local
      l[:label] = I18n.t(l[:path]+'.label', :scope => @co.tab.tab_type)
      l[:hint] = I18n.t(l[:path]+'.hint', :default => '', :scope => @co.tab.tab_type)
    else
      l[:label] = I18n.t(l[:path]+'.label') unless l[:label]
      l[:hint] = I18n.t(l[:path]+'.hint', :default => '') unless l[:hint]
    end
  end

  def dir_tabs(locals = {})
    raw render :partial => 'wa/dir_tabs', :locals => locals
  end

  def wa(cmd, l = {})
    l[:value] = Util.path_val(l[:path]) if !l[:value] && %w(color button_look map).include?(cmd)
    l[:cls] = '' unless l[:cls]
    raw render :partial => 'wa/'+cmd, :locals => l
  end

end

ruby_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
  def w(cmd, l = {})
    raw render :partial => 'w/'+cmd, :locals => l
  end

  # local widget
  def lw(cmd, l = {})
    co = RequestStore.store[:co]
    raw render :partial => "/tabs/answer_contest/lw/#{cmd}", :locals => l
  end
end

ruby_on_rails/app/views/helper/_facebook_init.haml
- locale = {pl: 'pl_PL', en: 'en_US'}
#fb-root
#ig-root
:javascript
  window.fbAsyncInit = function () {
      FB.init({
          appId:'#{@fb && @fb.app_id || GlobalTabParams::FB_PARAMS[:admin][0][:id]}',
          status: true,
          cookie: true,
          xfbml: true,
          oauth: true,
          channelUrl: '//socialinvaders.com/pl/channel'
      });
      FB.Canvas.setAutoGrow();

      var interval = setInterval(function() { // race condition
        if (typeof fbInitDef !== 'undefined') {
            fbInitDef.resolve();
            clearInterval(interval);
        }
      }, 100);
  };
  (function () {
      var e = document.createElement('script');
      e.async = true;
      e.src = document.location.protocol +
              '//connect.facebook.net/#{locale[I18n.locale]}/all.js';
      document.getElementById('fb-root').appendChild(e);
  }());

ruby_on_rails/app/views/helper/_opengraph.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<%= I18n.locale %>" lang="<%= I18n.locale %>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%- metadata.each do |property, content| %>
    <meta property="<%= property %>" content="<%= h(content) %>"/>
    <% end %>
</head>
<body>
Powinieneś zostać przekierowany... jeśli to się nie dzieje,
<a href="<%= raw redirect_url %>">kliknij tutaj</a>
<script type="text/javascript">
    top.location.href = '<%= raw redirect_url %>';
</script>
</body>
</html>

ruby_on_rails/app/views/helper/_redirect.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<%= I18n.locale %>" lang="<%= I18n.locale %>">
<body>
Powinieneś zostać przekierowany... jeśli to się nie dzieje,
<a href="<%= raw redirect_url %>">kliknij tutaj</a>
<script type="text/javascript">
    top.location.href = '<%= raw redirect_url %>';
</script>
</body>
</html>